function ()
TRUE = 1
FALSE = 0
STATE_IDLE = 0
STATE_MOVE = 1
STATE_ATTACK = 2
IDLE_TYPE_INVALID = -1
IDLE_TYPE_DEFAULT = 0
IDLE_TYPE_CAUTION = 1
IDLE_TYPE_BATTLE = 2
IDLE_TYPE_GUARD = 3
STATE_DEFAULT = 0
STATE_GUARD = 1
MOVE_STOP = 0
MOVE_WALK_FRONT = 1
MOVE_WALK_LEFT = 2
MOVE_WALK_RIGH = 3
MOVE_WALK_BACK = 4
MOVE_RUN = 5
INVALID_DAMAGE = 99999
IS_BLEND_ATTACK = FALSE
DAMAGE_LEVEL_SMALL = 1
DAMAGE_LEVEL_MIDDLE = 2
DAMAGE_LEVEL_LARGE = 3
DAMAGE_LEVEL_EXLARGE = 4
DAMAGE_LEVEL_PUSHED = 5
DAMAGE_LEVEL_DUSTERED = 6
DAMAGE_LEVEL_BLAST = 7
DAMAGE_LEVEL_MINIMUM = 8
DAMAGE_TYPE_DEATH = 2
DAMAGE_TYPE_PARRY = 5
DAMAGE_TYPE_SKYDEATH = 9
LADDER_HAND_RIGHT = 0
LADDER_HAND_LEFT = 1
LADDER_CONDITION_INVALID = -1
LADDER_CONDITION_START_BOTTOM = 0
LADDER_CONDITION_START_TOP = 1
LADDER_CONDITION_UP_RIGHT = 2
LADDER_CONDITION_UP_LEFT = 3
LADDER_CONDITION_DOWN_RIGHT = 4
LADDER_CONDITION_DOWN_LEFT = 5
LADDER_CONDITION_END_TOP = 6
LADDER_CONDITION_END_BOTTOM = 7
LADDER_CONDITION_IDLE_RIGHT = 8
LADDER_CONDITION_IDLE_LEFT = 9
LADDER_CONDITION_ATTACK_UP_RIGHT = 10
LADDER_CONDITION_ATTACK_UP_LEFT = 11
LADDER_CONDITION_ATTACK_DOWN_RIGHT = 12
LADDER_CONDITION_ATTACK_DOWN_LEFT = 13
LADDER_CONDITION_SLIDE_START_RIGHT = 14
LADDER_CONDITION_SLIDE_LOOP_RIGHT = 15
LADDER_CONDITION_SLIDE_STOP_RIGHT = 16
LADDER_CONDITION_SLIDE_START_LEFT = 17
LADDER_CONDITION_SLIDE_LOOP_LEFT = 18
LADDER_CONDITION_SLIDE_STOP_LEFT = 19
LADDER_CONDITION_SLIDE_LAND = 20
LADDER_CONDITION_DAMAGE = 21
LADDER_CONDITION_DAMAGE_LARGE = 22
LADDER_CONDITION_FALL_STAMINA = 23
LADDER_CONDITION_FALL_DEATH = 24
LADDER_REQUEST_START_BOTTOM = 7210
LADDER_REQUEST_START_TOP = 7220
LADDER_REQUEST_UP = 7210
LADDER_REQUEST_DOWN = 7220
LADDER_STATE_IDLE = 7240
LADDER_STATE_UP = 7210
LADDER_STATE_DOWN = 7220
LADDER_STATE_DEFAULT = 0
LADDER_COMMAND_UP = 0
LADDER_COMMAND_DOWN = 1
LADDER_COMMAND_INVALID = -1
DEATH_INDEX_DEFAULT = 0
DEATH_INDEX_WEAK = 1
DEATH_INDEX_SKY = 2
DEATH_INDEX_BLAST = 3
DEATH_INDEX_DUSTER = 4
DEATH_INDEX_LAND = 5
DEATH_INDEX_LANDFRONT = 6
DEATH_INDEX_LANDBACK = 7
GUARD_LEVEL_NONE = 0
GUARD_LEVEL_SMALL = 1
GUARD_LEVEL_MIDDLE = 2
GUARD_LEVEL_LARGE = 3
GUARD_LEVEL_EXLARGE = 4
DAMAGE_DIRECTION_LEFT = 0
DAMAGE_DIRECTION_RIGHT = 1
DAMAGE_DIRECTION_FRONT = 2
DAMAGE_DIRECTION_BACK = 3
FALL_INDEX_DEFAULT = 0
FALL_INDEX_FRONT = 1
FALL_INDEX_BACK = 2
LAND_INDEX_DEFAULT = 0
LAND_INDEX_HEAVY = 1
LAND_INDEX_FRONT = 2
LAND_INDEX_BACK = 3
IS_THROW_INVALID = 255
IS_THROW_DEFAULT = 0
IS_THROW_IDLE = 1
g_DebugCounter = 0
g_FrameCount = 0
g_TurnAngle = 0
g_MoveSpeedLevel = 0
g_IsLockon = false
g_MoveAngle = 0
g_IsGuard = FALSE
g_ActionNumber = -1
g_MoveState = -1
g_LadderFireCommand = LADDER_COMMAND_INVALID
global = {}
function dummy()
    
end

global.__index = function (table, element)
    return dummy
    
end

setmetatable(_G, global)

end
