TEAM_MEMBER_LIST_ROW_TYPE__NONE = -1
TEAM_MEMBER_LIST_ROW_TYPE__NEAR_TARGET = 0
TEAM_TARGET_POINT__INVALID = -1
TEAM_TARGET_POINT__F_IN = 0
TEAM_TARGET_POINT__L_IN = 1
TEAM_TARGET_POINT__B_IN = 2
TEAM_TARGET_POINT__R_IN = 3
TEAM_TARGET_POINT__F_OUT = 4
TEAM_TARGET_POINT__L_OUT = 5
TEAM_TARGET_POINT__B_OUT = 6
TEAM_TARGET_POINT__R_OUT = 7
TEAM_FMT_BASE_DIR__TARGET_DIR = 0
TEAM_FMT_BASE_DIR__LEADER_TO_TARGET = 1
return 
